version: '3.7'

volumes:
  front_node_modules:
  api_gems:
  volume_db:

networks: 
  network_app:

services:
  front:
      container_name: client

      build: 
        context: .
        dockerfile: ./client/Dockerfile
      
      ports: 
        - 8080:8080
      
      volumes:
        - ./client:/client
        - front_node_modules:/client/front_node_modules

      command: yarn dev

  back:
    container_name: api

    build: 
      context: .
      dockerfile: ./api/Dockerfile
    
    ports: 
      - 3000:3000

    volumes: 
      - ./api:/code
      - api_gems:/usr/local/bundle

    env_file: ./.env
    
    links:
      - db
    depends_on:
      - db

    networks: 
      - network_app
    
    command: rails server -p 3000 -b '0.0.0.0'

  db:
    container_name: database

    image: postgres:13

    volumes: 
      - volume_db:/var/lib/postgresql/data

    env_file: ./.env

    networks: 
      - network_app