name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Build
      run: docker-compose up --build -d

    # - name: RUN Client tests
    #   run: docker-compose run client yarn test:unit
        
    - name: Run API tests
      run: docker-compose run api rake test