name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build 
        run: docker-compose up --build -d
  
  tests:
    needs: [ build ]
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v2

    - name: Build Client Container
      run: |
        docker-compose up -d --build client
        
    - name: Run Client Tests
      run: |
        docker-compose run client yarn run test:unit

    - name: Build API
      run:  |
        docker-compose up -d --build db api
        
    - name: Run API Tests
      run: |
        docker-compose run -e "RAILS_ENV=test" api rake test

  sonarcloud:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build 
      run: docker-compose up --build -d
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
