name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build 
        run: docker-compose up --build -d

      - name: run client tests
        run: docker-compose run client yarn run test:unit

      - name: run api tests
        run: docker-compose run api bundle exec rails test