name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Build
      run: docker-compose up --build -d

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Run Client tests
      run: docker-compose run -e "NODE_ENV=test" client
        
    - name: Run API tests
      run: docker-compose run -e "RAILS_ENV=test" api