name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Build
      run: docker-compose up --build -d

  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Trabalho-Individual-2020-1

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby

      uses: ruby/setup-ruby@21351ecc0a7c196081abca5dc55b08f085efe09a
      with:
        ruby-version: 2.5.7
    - name: Run tests
      run: docker-compose bundle exec api rails 