name: Heroku

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login
    - name: Build and push
      with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "api-joaolucas"
          heroku_email: "joao.lucas.ssr@gmail.com"
        env:
          HD_APP_BASE: "api"